-- input_data table 스키마

CREATE TABLE `input_data` (
  `time` bigint DEFAULT NULL,
  `Tool` text,
  `stage` bigint DEFAULT NULL,
  `Lot` bigint DEFAULT NULL,
  `runnum` bigint DEFAULT NULL,
  `recipe` bigint DEFAULT NULL,
  `recipe_step` bigint DEFAULT NULL,
  `IONGAUGEPRESSURE` double DEFAULT NULL,
  `ETCHBEAMVOLTAGE` double DEFAULT NULL,
  `ETCHBEAMCURRENT` double DEFAULT NULL,
  `ETCHSUPPRESSORVOLTAGE` double DEFAULT NULL,
  `ETCHSUPPRESSORCURRENT` double DEFAULT NULL,
  `FLOWCOOLFLOWRATE` double DEFAULT NULL,
  `FLOWCOOLPRESSURE` double DEFAULT NULL,
  `ETCHGASCHANNEL1READBACK` double DEFAULT NULL,
  `ETCHPBNGASREADBACK` double DEFAULT NULL,
  `FIXTURETILTANGLE` double DEFAULT NULL,
  `ROTATIONSPEED` double DEFAULT NULL,
  `ACTUALROTATIONANGLE` double DEFAULT NULL,
  `FIXTURESHUTTERPOSITION` bigint DEFAULT NULL,
  `ETCHSOURCEUSAGE` double DEFAULT NULL,
  `ETCHAUXSOURCETIMER` double DEFAULT NULL,
  `ETCHAUX2SOURCETIMER` double DEFAULT NULL,
  `ACTUALSTEPDURATION` double DEFAULT NULL,
  `input_time` datetime NOT NULL,
  PRIMARY KEY (`input_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


-- rul table 스키마

CREATE TABLE `rul` (
  `rul_time` double DEFAULT NULL,
  `input_time` datetime NOT NULL,
  PRIMARY KEY (`input_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci